# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the image.', max_length=50)),
                ('image', models.FileField(help_text='The image.', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('pull_quote', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('publish', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(projects.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Thumbnail for the skill.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Image')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(projects.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Website name.', max_length=50)),
                ('url', models.URLField(help_text='Website url.')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Website thumbnail.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Image')),
            ],
            bases=(projects.models.BaseModel, models.Model),
        ),
        migrations.AddField(
            model_name='project',
            name='related_links',
            field=models.ManyToManyField(help_text='Github or project site.', to='projects.Website'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='The skills your project is based on.', to='projects.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Thumbnail for the project.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Image'),
        ),
    ]
